# data/themes/mytheme.toml
name = "mytheme"

# Brand colors
primary = "#00207fff"
primary_light = "#00207fff"
primary_dark = "#00207fff"

# Background colors
background = "#ffffff"
background_dark = "#000000"

# Surface (cards, sections)
surface = "#f7f7f7"
surface_dark = "#000000"

# Text
text = "#000000"
text_dark = "#ffffff"

# Links
link = "#00207fff"
link_hover = "#00207fff"

# Menu
menu_primary = "#ffffff"
menu_text = "#000000"
menu_text_active = "#00207fff"
